# Generated by Django 5.0.4 on 2024-04-04 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='core_citize_title_e377da_idx')],
            },
        ),
        migrations.CreateModel(
            name='EducationalAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='core_educat_title_057d51_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='core_employ_title_24ef4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['address'],
                'indexes': [models.Index(fields=['address'], name='core_locati_address_e521f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('no_of_members', models.IntegerField(default=1)),
                ('total_family_income', models.IntegerField()),
                ('duration_of_residence', models.IntegerField(help_text='no of days')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='core_marita_title_b69667_idx')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact_no', models.CharField(max_length=11)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birthdate', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('citizenship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.citizenship')),
                ('educational_attainment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.educationalattainment')),
                ('employement_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employementstatus')),
                ('family', models.ManyToManyField(to='core.family')),
                ('marital_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.maritalstatus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['title'], name='core_family_title_aa7fec_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='core_member_name_d6e5ad_idx'),
        ),
    ]
