# Generated by Django 5.0.6 on 2024-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='location',
        ),
        migrations.AddField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalattainment',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='duration_of_residence',
            field=models.IntegerField(help_text='no of days', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='no_of_members',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='total_family_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
