# Generated by Django 4.2.11 on 2024-04-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployementStatus',
            new_name='EmploymentStatus',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='employement_status',
            new_name='employment_status',
        ),
        migrations.RenameIndex(
            model_name='employmentstatus',
            new_name='core_employ_title_fbf287_idx',
            old_name='core_employ_title_24ef4a_idx',
        ),
    ]
