# Generated by Django 4.2.11 on 2024-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_employementstatus_employmentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
