# Generated by Django 4.2.11 on 2024-04-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.citizenship'),
        ),
        migrations.AlterField(
            model_name='member',
            name='educational_attainment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.educationalattainment'),
        ),
        migrations.AlterField(
            model_name='member',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employmentstatus'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maritalstatus'),
        ),
    ]
